server:
  port: 8801

spring:
  application:
    name: enreka-client-001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:8761/eureka/
  instance:
    hostname: eurekaclient
#debug: true

