server:
  port: 8803

spring:
  application:
    name: enreka-client-8803


eureka:
  client:
    service-url:
      default-zone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/,http://eureka03:8763/eureka/
  instance:
    hostname: eurekaclient



info:
  name: ${spring.application.name}